on:
  push:
    branches:
      - 'main'

name: build
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env
        run: |
          echo "HUGO=$(wget -qO- https://api.github.com/repos/gohugoio/hugo/tags | grep 'name' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV

      - name: Start build
        run: |
          wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/tags/${{ env.HUGO }} | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | grep "Linux-64bit.tar.gz" | grep "extended" | wget -O hugo.tar.gz -i -
          tar -zxvf hugo.tar.gz
          rm -rfv hugo.tar.gz LICENSE README.md
          chmod +x hugo
          ./hugo
          rm -rfv hugo

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: public